// <auto-generated />
using System;
using CadastroMedicoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroMedicoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210209225204_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CadastroMedicoApi.Models.CidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "PR",
                            Nome = "Londrina"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "PR",
                            Nome = "Maringa"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "SP",
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "RJ",
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "RS",
                            Nome = "Gramado"
                        },
                        new
                        {
                            Id = 6,
                            Estado = "SC",
                            Nome = "Florianopolis"
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cardiologista"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Podologia"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Otorrinolaringologia"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Pediatria"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Geral"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ortopedia"
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoCidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedicoEspecialidadeEspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedicoEspecialidadeMedicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("MedicoEspecialidadeMedicoId", "MedicoEspecialidadeEspecialidadeId");

                    b.ToTable("MedicoCidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            CidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            CidadeId = 5
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("MedicoEspecialidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            EspecialidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            EspecialidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            EspecialidadeId = 5
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "965669",
                            Nome = "Zoro",
                            Telefone = "541231849"
                        },
                        new
                        {
                            Id = 2,
                            Crm = "968549",
                            Nome = "Vegeta",
                            Telefone = "321149366"
                        },
                        new
                        {
                            Id = 3,
                            Crm = "155459",
                            Nome = "Asta",
                            Telefone = "358949544"
                        },
                        new
                        {
                            Id = 4,
                            Crm = "969549",
                            Nome = "Midoriya",
                            Telefone = "6585988523"
                        },
                        new
                        {
                            Id = 5,
                            Crm = "968215",
                            Nome = "Kakashi",
                            Telefone = "928645862"
                        },
                        new
                        {
                            Id = 6,
                            Crm = "056486",
                            Nome = "Ichigo",
                            Telefone = "588458852"
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.PrivilegioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Privilegios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Master"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ADM"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "User"
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "D.Luffy",
                            Nome = "Zoro",
                            PrivilegioId = 3,
                            Senha = "541231849"
                        },
                        new
                        {
                            Id = 2,
                            Login = "SSJ.Goku",
                            Nome = "Goku",
                            PrivilegioId = 4,
                            Senha = "321149366"
                        },
                        new
                        {
                            Id = 3,
                            Login = "Yami.Clover",
                            Nome = "Yami",
                            PrivilegioId = 6,
                            Senha = "358949544"
                        },
                        new
                        {
                            Id = 4,
                            Login = "Bakugou.Hero",
                            Nome = "Bakugou",
                            PrivilegioId = 5,
                            Senha = "6585988523"
                        },
                        new
                        {
                            Id = 5,
                            Login = "Sasuke.Amaterasu",
                            Nome = "Sasuke",
                            PrivilegioId = 1,
                            Senha = "928645862"
                        },
                        new
                        {
                            Id = 6,
                            Login = "Zaraki.Bankai",
                            Nome = "Zaraki",
                            PrivilegioId = 2,
                            Senha = "588458852"
                        });
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoCidade", b =>
                {
                    b.HasOne("CadastroMedicoApi.Models.CidadeModel", "Cidade")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadastroMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadastroMedicoApi.Models.MedicoEspecialidade", null)
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoEspecialidadeMedicoId", "MedicoEspecialidadeEspecialidadeId");

                    b.Navigation("Cidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.HasOne("CadastroMedicoApi.Models.EspecialidadeModel", "Especialidade")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadastroMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.CidadeModel", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Navigation("MedicoEspecialidade");
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("CadastroMedicoApi.Models.MedicoModel", b =>
                {
                    b.Navigation("MedicoCidade");

                    b.Navigation("MedicoEspecialidade");
                });
#pragma warning restore 612, 618
        }
    }
}
